CC = gcc
CFLAGS = -Wall -g

.DEFAULT_GOAL := help

.PHONY: help
help:
	@echo "Usage:"
	@echo "make exercise1"
	@echo "make exercise2"
	@echo "make exercise3"

exercise1: exercise1.c

exercise2: exercise2.c

exercise3: exercise3.c

clean:
	rm -f *.o
	rm -f *.out
	rm -f exercise1
	rm -f exercise2
	rm -f exercise3
